// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.3.0
// source: proto/blackhole.proto

package blackhole

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlackholeClient is the client API for Blackhole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlackholeClient interface {
	TestEndpoint(ctx context.Context, in *TestEndpointRequest, opts ...grpc.CallOption) (*TestEndpointResponse, error)
}

type blackholeClient struct {
	cc grpc.ClientConnInterface
}

func NewBlackholeClient(cc grpc.ClientConnInterface) BlackholeClient {
	return &blackholeClient{cc}
}

func (c *blackholeClient) TestEndpoint(ctx context.Context, in *TestEndpointRequest, opts ...grpc.CallOption) (*TestEndpointResponse, error) {
	out := new(TestEndpointResponse)
	err := c.cc.Invoke(ctx, "/C12S.Blackhole.Blackhole/testEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlackholeServer is the server API for Blackhole service.
// All implementations must embed UnimplementedBlackholeServer
// for forward compatibility
type BlackholeServer interface {
	TestEndpoint(context.Context, *TestEndpointRequest) (*TestEndpointResponse, error)
	mustEmbedUnimplementedBlackholeServer()
}

// UnimplementedBlackholeServer must be embedded to have forward compatible implementations.
type UnimplementedBlackholeServer struct {
}

func (UnimplementedBlackholeServer) TestEndpoint(context.Context, *TestEndpointRequest) (*TestEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestEndpoint not implemented")
}
func (UnimplementedBlackholeServer) mustEmbedUnimplementedBlackholeServer() {}

// UnsafeBlackholeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlackholeServer will
// result in compilation errors.
type UnsafeBlackholeServer interface {
	mustEmbedUnimplementedBlackholeServer()
}

func RegisterBlackholeServer(s grpc.ServiceRegistrar, srv BlackholeServer) {
	s.RegisterService(&Blackhole_ServiceDesc, srv)
}

func _Blackhole_TestEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlackholeServer).TestEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/C12S.Blackhole.Blackhole/testEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlackholeServer).TestEndpoint(ctx, req.(*TestEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Blackhole_ServiceDesc is the grpc.ServiceDesc for Blackhole service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blackhole_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "C12S.Blackhole.Blackhole",
	HandlerType: (*BlackholeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "testEndpoint",
			Handler:    _Blackhole_TestEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/blackhole.proto",
}
