// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blackhole.proto

package blackhole

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestEndpointRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestEndpointRequest) Reset()         { *m = TestEndpointRequest{} }
func (m *TestEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*TestEndpointRequest) ProtoMessage()    {}
func (*TestEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_83597fd9eb1aeb6f, []int{0}
}

func (m *TestEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestEndpointRequest.Unmarshal(m, b)
}
func (m *TestEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestEndpointRequest.Marshal(b, m, deterministic)
}
func (m *TestEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestEndpointRequest.Merge(m, src)
}
func (m *TestEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_TestEndpointRequest.Size(m)
}
func (m *TestEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestEndpointRequest proto.InternalMessageInfo

func (m *TestEndpointRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type TestEndpointResponse struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestEndpointResponse) Reset()         { *m = TestEndpointResponse{} }
func (m *TestEndpointResponse) String() string { return proto.CompactTextString(m) }
func (*TestEndpointResponse) ProtoMessage()    {}
func (*TestEndpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_83597fd9eb1aeb6f, []int{1}
}

func (m *TestEndpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestEndpointResponse.Unmarshal(m, b)
}
func (m *TestEndpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestEndpointResponse.Marshal(b, m, deterministic)
}
func (m *TestEndpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestEndpointResponse.Merge(m, src)
}
func (m *TestEndpointResponse) XXX_Size() int {
	return xxx_messageInfo_TestEndpointResponse.Size(m)
}
func (m *TestEndpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestEndpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestEndpointResponse proto.InternalMessageInfo

func (m *TestEndpointResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*TestEndpointRequest)(nil), "C12S.Blackhole.testEndpointRequest")
	proto.RegisterType((*TestEndpointResponse)(nil), "C12S.Blackhole.testEndpointResponse")
}

func init() { proto.RegisterFile("proto/blackhole.proto", fileDescriptor_83597fd9eb1aeb6f) }

var fileDescriptor_83597fd9eb1aeb6f = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xca, 0x49, 0x4c, 0xce, 0xce, 0xc8, 0xcf, 0x49, 0xd5, 0x03, 0xf3, 0x85, 0xf8,
	0x9c, 0x0d, 0x8d, 0x82, 0xf5, 0x9c, 0x60, 0xa2, 0x4a, 0x9a, 0x5c, 0xc2, 0x25, 0xa9, 0xc5, 0x25,
	0xae, 0x79, 0x29, 0x05, 0xf9, 0x99, 0x79, 0x25, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42,
	0x42, 0x5c, 0x2c, 0x25, 0xa9, 0x15, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6,
	0x92, 0x16, 0x97, 0x08, 0xaa, 0xd2, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x6c, 0x6a, 0x8d, 0xd2,
	0xb8, 0x38, 0xe1, 0x76, 0x08, 0x45, 0x72, 0xf1, 0x20, 0x6b, 0x14, 0x52, 0xd6, 0x43, 0x75, 0x84,
	0x1e, 0x16, 0x17, 0x48, 0xa9, 0xe0, 0x57, 0x04, 0xb1, 0xdb, 0x89, 0x37, 0x8a, 0x5b, 0x0f, 0xe1,
	0xc7, 0x24, 0x36, 0xb0, 0x27, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xce, 0x53, 0x91, 0x29,
	0xfd, 0x00, 0x00, 0x00,
}
