// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blackhole.proto

package blackhole

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task_State int32

const (
	Task_RECEIVED      Task_State = 0
	Task_PROCESSING    Task_State = 1
	Task_RETRY_TIMEOUT Task_State = 2
	Task_FINISHED      Task_State = 3
	Task_FAILED        Task_State = 4
	Task_DELETED       Task_State = 5
)

var Task_State_name = map[int32]string{
	0: "RECEIVED",
	1: "PROCESSING",
	2: "RETRY_TIMEOUT",
	3: "FINISHED",
	4: "FAILED",
	5: "DELETED",
}

var Task_State_value = map[string]int32{
	"RECEIVED":      0,
	"PROCESSING":    1,
	"RETRY_TIMEOUT": 2,
	"FINISHED":      3,
	"FAILED":        4,
	"DELETED":       5,
}

func (x Task_State) String() string {
	return proto.EnumName(Task_State_name, int32(x))
}

func (Task_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83597fd9eb1aeb6f, []int{2, 0}
}

type TaskId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskId) Reset()         { *m = TaskId{} }
func (m *TaskId) String() string { return proto.CompactTextString(m) }
func (*TaskId) ProtoMessage()    {}
func (*TaskId) Descriptor() ([]byte, []int) {
	return fileDescriptor_83597fd9eb1aeb6f, []int{0}
}

func (m *TaskId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskId.Unmarshal(m, b)
}
func (m *TaskId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskId.Marshal(b, m, deterministic)
}
func (m *TaskId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskId.Merge(m, src)
}
func (m *TaskId) XXX_Size() int {
	return xxx_messageInfo_TaskId.Size(m)
}
func (m *TaskId) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskId.DiscardUnknown(m)
}

var xxx_messageInfo_TaskId proto.InternalMessageInfo

func (m *TaskId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type WorkerDestination struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerDestination) Reset()         { *m = WorkerDestination{} }
func (m *WorkerDestination) String() string { return proto.CompactTextString(m) }
func (*WorkerDestination) ProtoMessage()    {}
func (*WorkerDestination) Descriptor() ([]byte, []int) {
	return fileDescriptor_83597fd9eb1aeb6f, []int{1}
}

func (m *WorkerDestination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerDestination.Unmarshal(m, b)
}
func (m *WorkerDestination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerDestination.Marshal(b, m, deterministic)
}
func (m *WorkerDestination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerDestination.Merge(m, src)
}
func (m *WorkerDestination) XXX_Size() int {
	return xxx_messageInfo_WorkerDestination.Size(m)
}
func (m *WorkerDestination) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerDestination.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerDestination proto.InternalMessageInfo

func (m *WorkerDestination) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *WorkerDestination) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type Task struct {
	Id                string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	QueueId           string             `protobuf:"bytes,3,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	WorkerDestination *WorkerDestination `protobuf:"bytes,4,opt,name=worker_destination,json=workerDestination,proto3" json:"worker_destination,omitempty"`
	Payload           string             `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	MaxRetries        int32              `protobuf:"varint,6,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	// Next two fields are in milliseconds
	RetryDelay           int32      `protobuf:"varint,7,opt,name=retry_delay,json=retryDelay,proto3" json:"retry_delay,omitempty"`
	Timeout              int32      `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	State                Task_State `protobuf:"varint,9,opt,name=state,proto3,enum=C12S.Blackhole.Task_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_83597fd9eb1aeb6f, []int{2}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetQueueId() string {
	if m != nil {
		return m.QueueId
	}
	return ""
}

func (m *Task) GetWorkerDestination() *WorkerDestination {
	if m != nil {
		return m.WorkerDestination
	}
	return nil
}

func (m *Task) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *Task) GetMaxRetries() int32 {
	if m != nil {
		return m.MaxRetries
	}
	return 0
}

func (m *Task) GetRetryDelay() int32 {
	if m != nil {
		return m.RetryDelay
	}
	return 0
}

func (m *Task) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Task) GetState() Task_State {
	if m != nil {
		return m.State
	}
	return Task_RECEIVED
}

type TaskQueue struct {
	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BucketSize int32  `protobuf:"varint,3,opt,name=bucket_size,json=bucketSize,proto3" json:"bucket_size,omitempty"`
	// In milliseconds
	RefreshRate          int32    `protobuf:"varint,4,opt,name=refresh_rate,json=refreshRate,proto3" json:"refresh_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskQueue) Reset()         { *m = TaskQueue{} }
func (m *TaskQueue) String() string { return proto.CompactTextString(m) }
func (*TaskQueue) ProtoMessage()    {}
func (*TaskQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_83597fd9eb1aeb6f, []int{3}
}

func (m *TaskQueue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskQueue.Unmarshal(m, b)
}
func (m *TaskQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskQueue.Marshal(b, m, deterministic)
}
func (m *TaskQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskQueue.Merge(m, src)
}
func (m *TaskQueue) XXX_Size() int {
	return xxx_messageInfo_TaskQueue.Size(m)
}
func (m *TaskQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskQueue.DiscardUnknown(m)
}

var xxx_messageInfo_TaskQueue proto.InternalMessageInfo

func (m *TaskQueue) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskQueue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskQueue) GetBucketSize() int32 {
	if m != nil {
		return m.BucketSize
	}
	return 0
}

func (m *TaskQueue) GetRefreshRate() int32 {
	if m != nil {
		return m.RefreshRate
	}
	return 0
}

func init() {
	proto.RegisterEnum("C12S.Blackhole.Task_State", Task_State_name, Task_State_value)
	proto.RegisterType((*TaskId)(nil), "C12S.Blackhole.TaskId")
	proto.RegisterType((*WorkerDestination)(nil), "C12S.Blackhole.WorkerDestination")
	proto.RegisterType((*Task)(nil), "C12S.Blackhole.Task")
	proto.RegisterType((*TaskQueue)(nil), "C12S.Blackhole.TaskQueue")
}

func init() { proto.RegisterFile("proto/blackhole.proto", fileDescriptor_83597fd9eb1aeb6f) }

var fileDescriptor_83597fd9eb1aeb6f = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x26, 0x6d, 0xd3, 0xb4, 0x97, 0xad, 0xa4, 0x16, 0x4c, 0x5e, 0x5f, 0xd6, 0xf5, 0xa9, 0x4f,
	0x01, 0x8a, 0x10, 0x12, 0x12, 0x0f, 0x5b, 0xe3, 0x95, 0x48, 0x63, 0x1b, 0x4e, 0x01, 0xc1, 0x4b,
	0xe4, 0xce, 0x87, 0x1a, 0x35, 0x6d, 0x46, 0xe2, 0x6a, 0xeb, 0x9e, 0xf8, 0x29, 0xfc, 0x54, 0x64,
	0xa7, 0x63, 0x62, 0xeb, 0x24, 0xb4, 0xb7, 0xfb, 0xbe, 0xfb, 0xee, 0x7c, 0xf7, 0xd9, 0x86, 0xe7,
	0x17, 0x79, 0xa6, 0xb2, 0x17, 0x93, 0x54, 0x9c, 0xcf, 0xa6, 0x59, 0x8a, 0xbe, 0xc1, 0xa4, 0x35,
	0x7c, 0x35, 0x88, 0xfc, 0xc3, 0x1b, 0xb6, 0x47, 0xa1, 0x3e, 0x16, 0xc5, 0x2c, 0x94, 0xa4, 0x05,
	0x95, 0x44, 0x52, 0xab, 0x6b, 0xf5, 0x9b, 0xbc, 0x92, 0xc8, 0xde, 0x7b, 0x68, 0x7f, 0xcd, 0xf2,
	0x19, 0xe6, 0x01, 0x16, 0x2a, 0x59, 0x08, 0x95, 0x64, 0x0b, 0xe2, 0x41, 0x75, 0x99, 0xa7, 0x6b,
	0x95, 0x0e, 0xc9, 0x0e, 0xd4, 0xe7, 0xa8, 0xa6, 0x99, 0xa4, 0x15, 0x43, 0xae, 0x51, 0xef, 0x77,
	0x15, 0x6a, 0xba, 0xf3, 0xdd, 0xbe, 0x84, 0x40, 0x6d, 0x21, 0xe6, 0xb8, 0x96, 0x9b, 0x98, 0xec,
	0x42, 0xe3, 0xe7, 0x12, 0x97, 0x18, 0x27, 0x92, 0x56, 0x0d, 0xef, 0x18, 0x1c, 0x4a, 0x72, 0x06,
	0xe4, 0xd2, 0x8c, 0x11, 0xcb, 0xdb, 0x39, 0x68, 0xad, 0x6b, 0xf5, 0xdd, 0xc1, 0xbe, 0xff, 0xef,
	0x36, 0xfe, 0xbd, 0x81, 0x79, 0xfb, 0xf2, 0xde, 0x0e, 0x14, 0x9c, 0x0b, 0xb1, 0x4a, 0x33, 0x21,
	0xa9, 0x5d, 0x9e, 0xb5, 0x86, 0x64, 0x0f, 0xdc, 0xb9, 0xb8, 0x8a, 0x73, 0x54, 0x79, 0x82, 0x05,
	0xad, 0x77, 0xad, 0xbe, 0xcd, 0x61, 0x2e, 0xae, 0x78, 0xc9, 0x68, 0x81, 0x4e, 0xae, 0x62, 0x89,
	0xa9, 0x58, 0x51, 0xa7, 0x14, 0x18, 0x2a, 0xd0, 0x8c, 0xee, 0xad, 0x92, 0x39, 0x66, 0x4b, 0x45,
	0x1b, 0x26, 0x79, 0x03, 0xc9, 0x4b, 0xb0, 0x0b, 0x25, 0x14, 0xd2, 0x66, 0xd7, 0xea, 0xb7, 0x06,
	0x9d, 0xbb, 0xa3, 0x6b, 0xaf, 0xfc, 0x48, 0x2b, 0x78, 0x29, 0xec, 0xc5, 0x60, 0x1b, 0x4c, 0xb6,
	0xa0, 0xc1, 0xd9, 0x90, 0x85, 0x5f, 0x58, 0xe0, 0x3d, 0x21, 0x2d, 0x80, 0x33, 0x7e, 0x3a, 0x64,
	0x51, 0x14, 0x9e, 0x8c, 0x3c, 0x8b, 0xb4, 0x61, 0x9b, 0xb3, 0x31, 0xff, 0x16, 0x8f, 0xc3, 0x8f,
	0xec, 0xf4, 0xf3, 0xd8, 0xab, 0xe8, 0x82, 0xa3, 0xf0, 0x24, 0x8c, 0x3e, 0xb0, 0xc0, 0xab, 0x12,
	0x80, 0xfa, 0xd1, 0x41, 0x78, 0xcc, 0x02, 0xaf, 0x46, 0x5c, 0x70, 0x02, 0x76, 0xcc, 0xc6, 0x2c,
	0xf0, 0xec, 0x5e, 0x01, 0x4d, 0x7d, 0xea, 0x27, 0xed, 0xf4, 0x7f, 0x5d, 0xd3, 0x1e, 0xb8, 0x93,
	0xe5, 0xf9, 0x0c, 0x55, 0x5c, 0x24, 0xd7, 0x68, 0x6e, 0xca, 0xe6, 0x50, 0x52, 0x51, 0x72, 0x8d,
	0x64, 0x1f, 0xb6, 0x72, 0xfc, 0x91, 0x63, 0x31, 0x8d, 0x73, 0xbd, 0x6b, 0xcd, 0x28, 0xdc, 0x35,
	0xc7, 0x85, 0xc2, 0xc1, 0xaf, 0x0a, 0x34, 0xff, 0x6e, 0x4d, 0xde, 0x80, 0x73, 0x20, 0xa5, 0x79,
	0x27, 0xcf, 0x36, 0x39, 0xd2, 0xd9, 0xc8, 0x92, 0xb7, 0xe0, 0x8c, 0x50, 0x99, 0x70, 0x67, 0x93,
	0x20, 0x94, 0x0f, 0x14, 0xbe, 0x03, 0x08, 0x30, 0x45, 0x85, 0x8f, 0xa8, 0x1d, 0xc1, 0xd3, 0x61,
	0x8e, 0xa2, 0xac, 0x2d, 0x4d, 0xdb, 0xdd, 0x24, 0x34, 0xa9, 0xce, 0xc3, 0xa9, 0xc3, 0xed, 0xef,
	0xae, 0x7f, 0xfb, 0x31, 0x27, 0x75, 0xf3, 0x33, 0x5f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xa3,
	0xd6, 0xb4, 0xf4, 0xb2, 0x03, 0x00, 0x00,
}
