// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blackhole.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	blackhole.proto

It has these top-level messages:
	Strategy
	KV
	Selector
	Data
	Metadata
	PutTask
	PutReq
	Task
	Resp
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enums
type TaskKind int32

const (
	TaskKind_CONFIGS    TaskKind = 0
	TaskKind_ACTIONS    TaskKind = 1
	TaskKind_SECRETS    TaskKind = 2
	TaskKind_NAMESPACES TaskKind = 3
)

var TaskKind_name = map[int32]string{
	0: "CONFIGS",
	1: "ACTIONS",
	2: "SECRETS",
	3: "NAMESPACES",
}
var TaskKind_value = map[string]int32{
	"CONFIGS":    0,
	"ACTIONS":    1,
	"SECRETS":    2,
	"NAMESPACES": 3,
}

func (x TaskKind) String() string {
	return proto.EnumName(TaskKind_name, int32(x))
}
func (TaskKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PayloadKind int32

const (
	PayloadKind_FILE   PayloadKind = 0
	PayloadKind_ENV    PayloadKind = 1
	PayloadKind_ACTION PayloadKind = 2
)

var PayloadKind_name = map[int32]string{
	0: "FILE",
	1: "ENV",
	2: "ACTION",
}
var PayloadKind_value = map[string]int32{
	"FILE":   0,
	"ENV":    1,
	"ACTION": 2,
}

func (x PayloadKind) String() string {
	return proto.EnumName(PayloadKind_name, int32(x))
}
func (PayloadKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type StrategyKind int32

const (
	StrategyKind_AT_ONCE        StrategyKind = 0
	StrategyKind_ROLLING_UPDATE StrategyKind = 1
)

var StrategyKind_name = map[int32]string{
	0: "AT_ONCE",
	1: "ROLLING_UPDATE",
}
var StrategyKind_value = map[string]int32{
	"AT_ONCE":        0,
	"ROLLING_UPDATE": 1,
}

func (x StrategyKind) String() string {
	return proto.EnumName(StrategyKind_name, int32(x))
}
func (StrategyKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CompareKind int32

const (
	CompareKind_ALL CompareKind = 0
	CompareKind_ANY CompareKind = 1
)

var CompareKind_name = map[int32]string{
	0: "ALL",
	1: "ANY",
}
var CompareKind_value = map[string]int32{
	"ALL": 0,
	"ANY": 1,
}

func (x CompareKind) String() string {
	return proto.EnumName(CompareKind_name, int32(x))
}
func (CompareKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type TaskStatus int32

const (
	TaskStatus_Waiting TaskStatus = 0
	TaskStatus_Working TaskStatus = 1
	TaskStatus_Done    TaskStatus = 2
)

var TaskStatus_name = map[int32]string{
	0: "Waiting",
	1: "Working",
	2: "Done",
}
var TaskStatus_value = map[string]int32{
	"Waiting": 0,
	"Working": 1,
	"Done":    2,
}

func (x TaskStatus) String() string {
	return proto.EnumName(TaskStatus_name, int32(x))
}
func (TaskStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// Request helper messages
type Strategy struct {
	Type string       `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Kind StrategyKind `protobuf:"varint,2,opt,name=kind,enum=service.StrategyKind" json:"kind,omitempty"`
}

func (m *Strategy) Reset()                    { *m = Strategy{} }
func (m *Strategy) String() string            { return proto.CompactTextString(m) }
func (*Strategy) ProtoMessage()               {}
func (*Strategy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Strategy) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Strategy) GetKind() StrategyKind {
	if m != nil {
		return m.Kind
	}
	return StrategyKind_AT_ONCE
}

type KV struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *KV) Reset()                    { *m = KV{} }
func (m *KV) String() string            { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()               {}
func (*KV) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *KV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Selector struct {
	Kind   CompareKind `protobuf:"varint,1,opt,name=kind,enum=service.CompareKind" json:"kind,omitempty"`
	Labels []*KV       `protobuf:"bytes,2,rep,name=labels" json:"labels,omitempty"`
}

func (m *Selector) Reset()                    { *m = Selector{} }
func (m *Selector) String() string            { return proto.CompactTextString(m) }
func (*Selector) ProtoMessage()               {}
func (*Selector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Selector) GetKind() CompareKind {
	if m != nil {
		return m.Kind
	}
	return CompareKind_ALL
}

func (m *Selector) GetLabels() []*KV {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Data struct {
	Kind  PayloadKind `protobuf:"varint,1,opt,name=kind,enum=service.PayloadKind" json:"kind,omitempty"`
	Value []string    `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Data) GetKind() PayloadKind {
	if m != nil {
		return m.Kind
	}
	return PayloadKind_FILE
}

func (m *Data) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type Metadata struct {
	TaskName            string `protobuf:"bytes,1,opt,name=taskName" json:"taskName,omitempty"`
	Timestamp           int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Namespace           string `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	ForceNamespaceQueue bool   `protobuf:"varint,4,opt,name=forceNamespaceQueue" json:"forceNamespaceQueue,omitempty"`
	Queue               string `protobuf:"bytes,5,opt,name=queue" json:"queue,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Metadata) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *Metadata) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Metadata) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Metadata) GetForceNamespaceQueue() bool {
	if m != nil {
		return m.ForceNamespaceQueue
	}
	return false
}

func (m *Metadata) GetQueue() string {
	if m != nil {
		return m.Queue
	}
	return ""
}

type PutTask struct {
	RegionId  string    `protobuf:"bytes,1,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	ClusterId string    `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId" json:"cluster_id,omitempty"`
	Strategy  *Strategy `protobuf:"bytes,3,opt,name=strategy" json:"strategy,omitempty"`
	Selector  *Selector `protobuf:"bytes,4,opt,name=selector" json:"selector,omitempty"`
	Data      *Data     `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *PutTask) Reset()                    { *m = PutTask{} }
func (m *PutTask) String() string            { return proto.CompactTextString(m) }
func (*PutTask) ProtoMessage()               {}
func (*PutTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PutTask) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *PutTask) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *PutTask) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

func (m *PutTask) GetSelector() *Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *PutTask) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

// Reques messages
type PutReq struct {
	Version string     `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	UserId  string     `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Kind    TaskKind   `protobuf:"varint,3,opt,name=kind,enum=service.TaskKind" json:"kind,omitempty"`
	Mtdata  *Metadata  `protobuf:"bytes,4,opt,name=mtdata" json:"mtdata,omitempty"`
	Tasks   []*PutTask `protobuf:"bytes,5,rep,name=tasks" json:"tasks,omitempty"`
}

func (m *PutReq) Reset()                    { *m = PutReq{} }
func (m *PutReq) String() string            { return proto.CompactTextString(m) }
func (*PutReq) ProtoMessage()               {}
func (*PutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PutReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PutReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PutReq) GetKind() TaskKind {
	if m != nil {
		return m.Kind
	}
	return TaskKind_CONFIGS
}

func (m *PutReq) GetMtdata() *Metadata {
	if m != nil {
		return m.Mtdata
	}
	return nil
}

func (m *PutReq) GetTasks() []*PutTask {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type Task struct {
	UserId    string     `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Kind      TaskKind   `protobuf:"varint,2,opt,name=kind,enum=service.TaskKind" json:"kind,omitempty"`
	Timestamp int64      `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Namespace string     `protobuf:"bytes,4,opt,name=namespace" json:"namespace,omitempty"`
	Task      *PutTask   `protobuf:"bytes,5,opt,name=task" json:"task,omitempty"`
	Status    TaskStatus `protobuf:"varint,6,opt,name=status,enum=service.TaskStatus" json:"status,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Task) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Task) GetKind() TaskKind {
	if m != nil {
		return m.Kind
	}
	return TaskKind_CONFIGS
}

func (m *Task) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Task) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Task) GetTask() *PutTask {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *Task) GetStatus() TaskStatus {
	if m != nil {
		return m.Status
	}
	return TaskStatus_Waiting
}

// Response message
type Resp struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Resp) Reset()                    { *m = Resp{} }
func (m *Resp) String() string            { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()               {}
func (*Resp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Resp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Strategy)(nil), "service.Strategy")
	proto.RegisterType((*KV)(nil), "service.KV")
	proto.RegisterType((*Selector)(nil), "service.Selector")
	proto.RegisterType((*Data)(nil), "service.Data")
	proto.RegisterType((*Metadata)(nil), "service.Metadata")
	proto.RegisterType((*PutTask)(nil), "service.PutTask")
	proto.RegisterType((*PutReq)(nil), "service.PutReq")
	proto.RegisterType((*Task)(nil), "service.Task")
	proto.RegisterType((*Resp)(nil), "service.Resp")
	proto.RegisterEnum("service.TaskKind", TaskKind_name, TaskKind_value)
	proto.RegisterEnum("service.PayloadKind", PayloadKind_name, PayloadKind_value)
	proto.RegisterEnum("service.StrategyKind", StrategyKind_name, StrategyKind_value)
	proto.RegisterEnum("service.CompareKind", CompareKind_name, CompareKind_value)
	proto.RegisterEnum("service.TaskStatus", TaskStatus_name, TaskStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BlackHoleService service

type BlackHoleServiceClient interface {
	Put(ctx context.Context, in *PutReq, opts ...grpc.CallOption) (*Resp, error)
}

type blackHoleServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlackHoleServiceClient(cc *grpc.ClientConn) BlackHoleServiceClient {
	return &blackHoleServiceClient{cc}
}

func (c *blackHoleServiceClient) Put(ctx context.Context, in *PutReq, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := grpc.Invoke(ctx, "/service.BlackHoleService/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BlackHoleService service

type BlackHoleServiceServer interface {
	Put(context.Context, *PutReq) (*Resp, error)
}

func RegisterBlackHoleServiceServer(s *grpc.Server, srv BlackHoleServiceServer) {
	s.RegisterService(&_BlackHoleService_serviceDesc, srv)
}

func _BlackHoleService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlackHoleServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.BlackHoleService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlackHoleServiceServer).Put(ctx, req.(*PutReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlackHoleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.BlackHoleService",
	HandlerType: (*BlackHoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _BlackHoleService_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blackhole.proto",
}

func init() { proto.RegisterFile("blackhole.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 731 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xdb, 0x72, 0xa3, 0x46,
	0x10, 0x35, 0x02, 0x21, 0xd4, 0x4a, 0x6c, 0x32, 0x76, 0x2a, 0x94, 0x93, 0x54, 0x14, 0x72, 0x93,
	0x15, 0xc7, 0x71, 0x29, 0x8f, 0x79, 0xd2, 0xca, 0xb2, 0x97, 0xb2, 0x8c, 0xb4, 0x83, 0xd6, 0x2e,
	0x3f, 0xb9, 0xc6, 0x62, 0x56, 0x4b, 0x09, 0x84, 0xcc, 0x0c, 0xae, 0xd2, 0x2f, 0xed, 0xfb, 0xfe,
	0xc2, 0xfe, 0xc1, 0xfe, 0xcf, 0xd6, 0x0c, 0x20, 0xf0, 0x65, 0xfd, 0x46, 0x4f, 0x9f, 0xe9, 0x3e,
	0x7d, 0x4e, 0x33, 0xb0, 0x73, 0x1b, 0x92, 0xd9, 0xe2, 0x7d, 0x1c, 0xd2, 0xa3, 0x55, 0x12, 0xf3,
	0x18, 0x35, 0x18, 0x4d, 0xee, 0x83, 0x19, 0xb5, 0x1d, 0x30, 0x3c, 0x9e, 0x10, 0x4e, 0xe7, 0x6b,
	0x84, 0x40, 0xe3, 0xeb, 0x15, 0xb5, 0x94, 0xb6, 0xd2, 0x69, 0x62, 0xf9, 0x8d, 0x0e, 0x40, 0x5b,
	0x04, 0x4b, 0xdf, 0xaa, 0xb5, 0x95, 0xce, 0x76, 0xef, 0xfb, 0xa3, 0xfc, 0xde, 0x51, 0x71, 0xe9,
	0x3c, 0x58, 0xfa, 0x58, 0x42, 0xec, 0x43, 0xa8, 0x9d, 0x5f, 0x22, 0x13, 0xd4, 0x05, 0x5d, 0xe7,
	0x35, 0xc4, 0x27, 0xda, 0x83, 0xfa, 0x3d, 0x09, 0x53, 0x2a, 0x6b, 0x34, 0x71, 0x16, 0xd8, 0xd7,
	0x60, 0x78, 0x34, 0xa4, 0x33, 0x1e, 0x27, 0xa8, 0x93, 0x37, 0x51, 0x64, 0x93, 0xbd, 0x4d, 0x93,
	0x41, 0x1c, 0xad, 0x48, 0x42, 0xcb, 0x1e, 0xe8, 0x37, 0xd0, 0x43, 0x72, 0x4b, 0x43, 0x66, 0xd5,
	0xda, 0x6a, 0xa7, 0xd5, 0x6b, 0x6d, 0xb0, 0xe7, 0x97, 0x38, 0x4f, 0xd9, 0xa7, 0xa0, 0x9d, 0x10,
	0x4e, 0xbe, 0x5a, 0x76, 0x42, 0xd6, 0x61, 0x4c, 0xfc, 0x4a, 0xd9, 0x0a, 0x45, 0xb5, 0xa4, 0xf8,
	0x41, 0x01, 0xe3, 0x82, 0x72, 0xe2, 0x8b, 0x62, 0xfb, 0x60, 0x70, 0xc2, 0x16, 0x2e, 0x89, 0x0a,
	0x81, 0x36, 0x31, 0xfa, 0x09, 0x9a, 0x3c, 0x88, 0x28, 0xe3, 0x24, 0x5a, 0xc9, 0x29, 0x55, 0x5c,
	0x1e, 0x88, 0xec, 0x92, 0x44, 0x94, 0xad, 0xc8, 0x8c, 0x5a, 0xaa, 0xbc, 0x5a, 0x1e, 0xa0, 0x63,
	0xd8, 0x7d, 0x17, 0x27, 0x33, 0xea, 0x16, 0x27, 0x6f, 0x52, 0x9a, 0x52, 0x4b, 0x6b, 0x2b, 0x1d,
	0x03, 0x3f, 0x97, 0x12, 0x64, 0xef, 0x24, 0xa6, 0x9e, 0xe9, 0x29, 0x03, 0xfb, 0x93, 0x02, 0x8d,
	0x49, 0xca, 0xa7, 0x84, 0x2d, 0xd0, 0x8f, 0xd0, 0x4c, 0xe8, 0x3c, 0x88, 0x97, 0x37, 0x81, 0x5f,
	0x90, 0xcd, 0x0e, 0x1c, 0x1f, 0xfd, 0x0c, 0x30, 0x0b, 0x53, 0xc6, 0x69, 0x22, 0xb2, 0x99, 0x27,
	0xcd, 0xfc, 0xc4, 0xf1, 0xd1, 0x3f, 0x60, 0xb0, 0xdc, 0x5b, 0x49, 0xb6, 0xd5, 0xfb, 0xee, 0x89,
	0xe9, 0x78, 0x03, 0x91, 0xf0, 0xdc, 0x46, 0xc9, 0xf9, 0x01, 0x3c, 0x4f, 0xe0, 0x0d, 0x04, 0xfd,
	0x0a, 0x9a, 0x50, 0x53, 0x52, 0x6f, 0xf5, 0xbe, 0xdd, 0x40, 0x85, 0x5f, 0x58, 0xa6, 0xec, 0x8f,
	0x0a, 0xe8, 0x93, 0x94, 0x63, 0x7a, 0x87, 0x2c, 0x68, 0xdc, 0xd3, 0x84, 0x05, 0xf1, 0x32, 0x9f,
	0xa2, 0x08, 0xd1, 0x0f, 0xd0, 0x48, 0x59, 0x75, 0x02, 0x5d, 0x84, 0x8e, 0x8f, 0xfe, 0xc8, 0x3d,
	0x57, 0xa5, 0xe7, 0x25, 0x17, 0xa1, 0x4b, 0xc5, 0xf0, 0x03, 0xd0, 0x23, 0x2e, 0x99, 0x3c, 0x26,
	0x5d, 0x18, 0x8e, 0x73, 0x00, 0xfa, 0x13, 0xea, 0xc2, 0x68, 0x66, 0xd5, 0xe5, 0xc6, 0x99, 0xe5,
	0x1a, 0x65, 0x6a, 0xe3, 0x2c, 0x6d, 0x7f, 0x56, 0x40, 0x93, 0xea, 0x57, 0xb8, 0x29, 0xcf, 0x72,
	0xab, 0xbd, 0xcc, 0xed, 0xc1, 0x36, 0xa9, 0x2f, 0x6e, 0x93, 0xf6, 0x78, 0x9b, 0x7e, 0x07, 0x4d,
	0xb0, 0xc9, 0xf5, 0x7d, 0xca, 0x55, 0x66, 0xd1, 0xdf, 0xa0, 0x33, 0x4e, 0x78, 0xca, 0x2c, 0x5d,
	0x52, 0xd9, 0x7d, 0x40, 0xc5, 0x93, 0x29, 0x9c, 0x43, 0x6c, 0x0b, 0x34, 0x4c, 0xd9, 0x4a, 0xfc,
	0xd8, 0x11, 0x9b, 0x17, 0x3f, 0x76, 0xc4, 0xe6, 0xdd, 0x3e, 0x18, 0x05, 0x75, 0xd4, 0x82, 0xc6,
	0x60, 0xec, 0x9e, 0x3a, 0x67, 0x9e, 0xb9, 0x25, 0x82, 0xfe, 0x60, 0xea, 0x8c, 0x5d, 0xcf, 0x54,
	0x44, 0xe0, 0x0d, 0x07, 0x78, 0x38, 0xf5, 0xcc, 0x1a, 0xda, 0x06, 0x70, 0xfb, 0x17, 0x43, 0x6f,
	0xd2, 0x1f, 0x0c, 0x3d, 0x53, 0xed, 0x1e, 0x42, 0xab, 0xf2, 0x37, 0x22, 0x03, 0xb4, 0x53, 0x67,
	0x34, 0x34, 0xb7, 0x50, 0x03, 0xd4, 0xa1, 0x7b, 0x69, 0x2a, 0x08, 0x40, 0xcf, 0x6a, 0x99, 0xb5,
	0xee, 0xbf, 0xf0, 0x4d, 0xf5, 0xdd, 0x91, 0x7d, 0xa6, 0x37, 0x63, 0x77, 0x20, 0x6e, 0x20, 0xd8,
	0xc6, 0xe3, 0xd1, 0xc8, 0x71, 0xcf, 0x6e, 0xde, 0x4e, 0x4e, 0xfa, 0xd3, 0xa1, 0xa9, 0x74, 0x7f,
	0x81, 0x56, 0xe5, 0x0d, 0x11, 0x45, 0xfb, 0xa3, 0x51, 0x56, 0xbd, 0xef, 0x5e, 0x9b, 0x4a, 0xf7,
	0x18, 0xa0, 0x1c, 0x59, 0xd4, 0xbb, 0x22, 0x01, 0x0f, 0x96, 0xf3, 0x6c, 0x88, 0xab, 0x38, 0x59,
	0x88, 0x40, 0x11, 0xc4, 0x4e, 0xe2, 0x25, 0x35, 0x6b, 0xbd, 0xff, 0xc1, 0x7c, 0x25, 0x1e, 0xd3,
	0xd7, 0x71, 0x48, 0xbd, 0x4c, 0x35, 0xf4, 0x17, 0xa8, 0x93, 0x94, 0xa3, 0x9d, 0xaa, 0xdc, 0x98,
	0xde, 0xed, 0x97, 0xfb, 0x2d, 0x14, 0xb4, 0xb7, 0x6e, 0x75, 0xf9, 0xfa, 0xfe, 0xf7, 0x25, 0x00,
	0x00, 0xff, 0xff, 0x90, 0x56, 0xde, 0x8d, 0x90, 0x05, 0x00, 0x00,
}
